### ISSUE TITLE
Katex support?

### ISSUE THREAD

**Issue by zhulunwu** [SimonDanisch/JSServe.jl#102]
It would be nice to display math , thanks.

**Comment by SimonDanisch** [comment]
It should be trivial to add something similar with JSServe:
https://github.com/piever/KaTeX.jl/blob/master/src/KaTeX.jl#L21

**Comment by SimonDanisch** [comment]
Closing this, since there is nothing actionable for me.
I wouldn't be against adding this to JSServe, I suppose, so PRs welcome.
