### ISSUE TITLE
"<br>"  not work

### ISSUE THREAD

**Issue by zhulunwu** [SimonDanisch/JSServe.jl#103]
Is this a deliberate design?(sorry for poor information at first)
I am developing an app for exams. the following is a simplified example:
```julia
using JSServe
using JSServe.DOM
using JSServe: Session
using Markdown

app = App() do session::Session
    text=md"""
    * this is a question, it has four choices:
    (A) first<br> 
    (B) second<br>
    (C) third<br>
    (D) fourth<br>
    """
    dom=DOM.p(text)
    return JSServe.DOM.div(JSServe.MarkdownCSS, JSServe.Styling, dom)
end
```
But it gives :
```
this is a question, it has four choices:

(A) first<br> (B) second<br> (C) third<br> (D) fourth<br>
```
Change `<br>` to "\n" still not work.  Add two spaces still not work

I have found that DOM.p has encode `<br>` to` "&#60;br&#62;" `
Though I made a replace from` "&#60;br&#62;" `to `<br>`  and solve the problem temporarily , still wander to know the correct solution.

**Comment by SimonDanisch** [comment]
what did you run, what happened, what did you expect?

**Comment by SimonDanisch** [comment]
Äh you shouldn't edit to add more information, since that doesn't give me a ping... Markdown is not html, so br in markdown doesn't work... `${DOM.br()}` may work
