### ISSUE TITLE
Setting listen_url to 0.0.0.0 makes the page fail to load (with WGLMakie)

### ISSUE THREAD

**Issue by iamazadi** [SimonDanisch/JSServe.jl#106]
Our program works properly using *WGLMakie* and *JSServe*, by ading the following lines at the top of the launch script:

```julia
import JSServe
JSServe.Page(exportable=true, offline=false, listen_port=8082)
using WGLMakie
WGLMakie.activate!()
```

Now, we know that `JSServe.Page(exportable=true, offline=false, listen_port=8082)` does the trick and the resulting browser display loads at **localhost:8080/browser-display** . So far so good and the web controls work good enough.

However, the problem is when we supply the keyword parameter *listen_url* with the value **0.0.0.0** so that the web app becomes available on local network. Setting *listen_url* in **JSServe.Page** as follows:

```julia
JSServe.Page(exportable=true, offline=true, listen_url="0.0.0.0", listen_port=8082)
```

This time, the web app does not work even on the host machine! Then, removing the keyword argument *listen_url* restores the working state of the app to the local host. Also, a browser page opens up automatically as soon as the program runs and the correct IP address of the host on local network is shown in the address bar, as a prefix to the supplied port number. For example: *http://192.168.0.101:8082/browser-display*

Turning to the docs, In the docstring
[Page](https://juliahub.com/docs/JSServe/GdItc/1.2.3/autodocs/#JSServe.Page-Tuple{})
and
[configure_server!](https://juliahub.com/docs/JSServe/GdItc/1.2.3/autodocs/#JSServe.configure_server!-Tuple{})
it looks like the values supplied are correct and it should work. We've also tried passing the keyword arguments *offline=false* and *exportable=false* and got the same result of a blank page. And, yes, firewall rules allow connections in and out of the specified port. We even went as far as forwarding the port number on the host IP using the router gateway settings.

And, no. The next line doesn't seem to work either:
```julia
JSServe.configure_server!(listen_url="0.0.0.0", listen_port=8082, forwarded_port=8082)
```

adapted from [Remote servers](http://makie.juliaplots.org/v0.15.2/documentation/remote/#wglmakie).

**Comment by SimonDanisch** [comment]
So, `Page` should only be used for notebooks. Use `JSServe.configure_server!` without `Page`.
It may work, but definitely brings things into a weird state.
Setting `offline=true` means "don't start a server", which works in a notebook, but not if you actually want to start a server accessible from the network.
So, can you try a minimal example that only uses `JSServe.configure_server!(listen_url="0.0.0.0"", listen_port=8082)` and if that doesn't work, post the minimal example here?

**Comment by iamazadi** [comment]
Here's a minimal example in order to see where the problem is in the tech stack.

```julia
# Serve WGLMakie via web

import JSServe
JSServe.configure_server!(listen_url="0.0.0.0", listen_port=8082) # does not work
# JSServe.configure_server!(listen_port=8082) # works
using WGLMakie
WGLMakie.activate!()

fig = Figure()

ax = Axis(fig[1, 1])

lsgrid = labelslidergrid!(
    fig,
    ["Voltage", "Current", "Resistance"],
    [0:0.1:10, 0:0.1:20, 0:0.1:30];
    formats = [x -> "$(round(x, digits = 1))$s" for s in ["V", "A", "Ω"]],
    width = 350,
    tellheight = false)

fig[1, 2] = lsgrid.layout

sliderobservables = [s.value for s in lsgrid.sliders]
bars = lift(sliderobservables...) do slvalues...
    [slvalues...]
end

barplot!(ax, bars, color = [:yellow, :orange, :red])
ylims!(ax, 0, 30)

set_close_to!(lsgrid.sliders[1], 5.3)
set_close_to!(lsgrid.sliders[2], 10.2)
set_close_to!(lsgrid.sliders[3], 15.9)

display(fig)
```

Run the experiment by saving the code in a script labeled *minimal_example,jl* and then executing the following command.
```bash
julia -i --project=. models/minimal_example.jl
```
After that a browser tab opens and the address below takes you to a blank page.
**http://192.168.0.101:8082/browser-display**

project status:
- JSServe v1.2.3
- WGLMakie v0.4.4

**Comment by SimonDanisch** [comment]
Ah ok, I was able to reproduce...
On windows, somehow `Sockets.getipaddr()` returns some weird address (looks like it returns the one from my docker installation, which is not even used).
That's what used here https://github.com/SimonDanisch/JSServe.jl/blob/master/src/JSServe.jl#L123, to set the external address automatically. The assumption is, whenever you set `listen_url="0.0.0.0"` you want to serve on your local network, so `external_url` needs to be set to the ip address of your local machine, so that it knows in the client what to connect to.
So to make things work on your machine, you need to set:
```julia
JSServe.configure_server!(listen_url="0.0.0.0", external_url="http://192.168.178.42:8082", listen_port=8082)
```
Now that I look at the code again, I wonder if we can't just get away without setting "external_url" and just use relative urls for all resources....

**Comment by iamazadi** [comment]
It works! Thanks for explaining the API and reproducing the problem to find a working setting.

**Comment by iamazadi** [comment]
I realized that the issue might reoccur in the future for others as well. So, I'll leave it open for another week in case I get a chance to try setting "external_url" and test that. Either it should result in a documentation edit or a PR to improve the interface.

**Comment by iamazadi** [comment]
A few days ago tested the development server setup with a dynamic DNS and it works in practice. That is, you can serve a Makie app via web using this method.
