### ISSUE TITLE
iframe display in Jupyter

### ISSUE THREAD

**Issue by alexriss** [SimonDanisch/JSServe.jl#110]
I am just starting with JSServe and trying to get the examples to run in jupyter (notebook and lab). For instance, when executing the examples in `basics.jl` (without the use of `browser_display()`), the output iframe is cut off (see images below, left).

I tracked it down to the use of "position:absolute;". Removing this CSS property (or setting it to "relative") seems to work (see below, right).

From skimming through the source, I am led to think that "Page()" might be the way to go for Jupyter. But I could not get that to work (error: "Warning: Waiting for page sessions to load. This can happen for the first cells to run, or is indicative of faulty state" - even if I call it at the very beginning.")

In general, the iframe display seems to be just fine in jupyter, but I wonder if the "position: absolute" is necessary for some other reason and whether it can be removed for jupyter output?

<table>
<tr>
	<td><img src="https://user-images.githubusercontent.com/1452525/136358833-76fb97a3-32a8-48ea-ae0e-2a3c7aa7aa5f.png" width="300"></td>
	<td><img src="https://user-images.githubusercontent.com/1452525/136359449-3f7f08f8-4601-4679-a17b-ad688d0696bf.png" width="300"></td>
</tr>
<tr>
	<td>current (with "position:absolute")</td>
	<td>without "position:absolute"</td>
</tr>
</table>

**Comment by SimonDanisch** [comment]
It has various downsides, but would be best configurable, since I guess there are some scenarios where its desirable... 
I think I removed it, because the logic to correctly resize the iframe to its content was pretty gruesome.... Maybe we can bring it back as a stop gap solution...

**Comment by davibarreira** [comment]
I'm also interested on this.

**Comment by alexriss** [comment]
yes, I did the qnd thing and just overloaded the function, using a fixed height:

function JSServe.iframe_html(server::JSServe.Server, session::JSServe.Session, route::String)
    # Display the route we just added in an iframe inline:
    url = JSServe.online_url(server, route)
    remote_origin = JSServe.online_url(server, "")
    # style = "position: absolute; width: 100%; height: 100%; padding: 0; overflow: hidden; border: none"
    style = "width: 100%; height: 480px; padding: 0; overflow: hidden; border: none"
    return DOM.iframe(src=url, id=session.id, style=style, scrolling="no")
end
