### ISSUE TITLE
Update HTTP.jl dep to v1.0+

### ISSUE THREAD

**Issue by PhyX-Meow** [SimonDanisch/JSServe.jl#131]
Hello, I'm using Makie.jl and Pluto.jl together. Pluto has update their dependent of HTTP.jl to v1.0.2 or later, but JSServe and WGLMakie still depends on v0.9. This prevented me to install latest Pluto. Could this get an update so we can work with HTTP v1.0+?
As a remainder, HTTP 1.0+ has integrated WebSockets functionalities as part of it, replacing old WebSockets.jl. So the version update may not be trivial.
Thank you.

**Comment by PhyX-Meow** [comment]
Seems WebSockets.jl is still maintained, in next version it will bump dep of HTTP to v1, so maybe we only need to wait that to be released. :)

**Comment by SimonDanisch** [comment]
Yeah, I switched a couple of times to HTTP only without relying on Websockets.jl... Gotta figure out in which branches that code has ended up, to not start from scratch when upgrading to HTTP 1.0

**Comment by PhyX-Meow** [comment]
Close since v2.0.0 works fine.
