### ISSUE TITLE
Permission denied for JSServe

### ISSUE THREAD

**Issue by vladdez** [SimonDanisch/JSServe.jl#157]
Windows 11, Version 22H2

I was trying to run volume.js from JSServe v2.1.0 `https://github.com/SimonDanisch/JSServe.jl#sd/bonito`
However I got this error after running `display(volume_app)`: 

ERROR: Asset C:\Users\Vlad\.julia\packages\JSServe\DXDwe\js_dependencies\Websocket.js needs bundling.
            If you've edited the asset, please load `Deno_jll` (e.g. `using Deno_jll, JSServe`),
            which is an optional dependency needed for Developing JSServe Assets.
            After that, assets should be bundled on precompile and whenever they're used after editing the asset.
            If you're just using a package, please open an issue with the Package maintainers,
            they must have forgotten bundling.

After `using Deno_jll` I got this error:
ERROR: SystemError: opening file "C:\\Users\\Vlad\\.julia\\packages\\JSServe\\DXDwe\\js_dependencies\\Websocket.bundled.js": Permission denied

After I run `]test JSServe`

Result:
![image](https://user-images.githubusercontent.com/33777074/226399113-96b9d78a-bc1e-49da-b065-a97275f740a0.png)

I run same code in admin mode (opened VSCode in Run as administrator mode):
![image](https://user-images.githubusercontent.com/33777074/226399832-17550a18-bed6-4564-91cd-4f45d6b92370.png)

**Comment by SimonDanisch** [comment]
Ah, damn, that's annoying ... I pushed a workaround!

**Comment by vladdez** [comment]
I saw you changed something in code yesterday. I checked it today: it is still the same problem.

**Comment by SimonDanisch** [comment]
Are you sure you pulled the new code? I had a similar problem yesterday were I could have sworn I updated, but somehow the old version was stilled used...

**Comment by behinger** [comment]
I just had the same error on a centos machine.
First I used add github..#sd/bonito - which I thought should work?
I pulled `  [824d6782] JSServe v2.1.0 `https://github.com/SimonDanisch/JSServe.jl#sd/bonito`   
but  I got the same exception: `Asset /home/bene/.julia/packages/JSServe/NTbp2/js_dependencies/Websocket.js needs bundling.`

next I used dev --local  + git track sd/bonito => works. Strange

**Comment by SimonDanisch** [comment]
Hm weird, I thought I got it working on two different machines after updating, so was pretty sure it should now work... But maybe there's still some subtlety left -.-

**Comment by behinger** [comment]
will trz it tomorrow - using dev worked for me so 🤷 

now I'm fighting with nginx and rerouting websockets ^^

**Comment by vladdez** [comment]
> ```julia
> test JSServe
> ```

For me it didn't work even in this mode.

**Comment by SimonDanisch** [comment]
Same error? On windows?

**Comment by SimonDanisch** [comment]
Ok, wow, I never actually fixed the issue, and it just looked like it because it suddenly worked on the systems I previously had that issue reproducibly. My best guess is that updating to a new version _may_ fix this issue, since it changes the file time stamps in an arbitrary way, and then it just keeps working, but it's actually purely by chance. 
The newest commit should _really_ fix this now, I hope :D

**Comment by vladdez** [comment]
Here is a gif showing how it look like for now: https://drive.google.com/file/d/1YFB3JZYsnq4H7A5iwRxkqwj2PHUgtQQN/view?usp=share_link

**Comment by vladdez** [comment]
JSServe       |  984    984  1m46.8s
     Testing JSServe tests passed 


Now everything works! Thank you very much!
