### ISSUE TITLE
More control over the developer tools panel for Electron windows?

### ISSUE THREAD

**Issue by ffevotte** [SimonDanisch/JSServe.jl#184]
Hello,

thanks for JSServe, this is very nice. I'm using it in combination to `Electron.jl`, and noticed that devtools are activated by default in https://github.com/SimonDanisch/JSServe.jl/blob/26cca0d3cc3ccbf4c9bfb73c8d6c97d027c6ae5c/src/HTTPServer/browser-display.jl#L116-L120

I can of course toggle devtools back off right after the Electron window is created, but this causes an (IMO annoying) flickering of the devtools panel.

So I'm not sure what the rationale behind this choice was, but would you please consider one of the following options:
1. do not automatically open devtools on Electron window creation, and document that `Electron.toggle_devtools(electron_display.window)` can be used to display it, or
2. provide a way for JSServe + Electron users to decide whether they want the devtools panel to be open by default at window creation. This could perhaps be an additional field in the `ElectronDisplay` instance, which users could set via a kwarg in `use_electron_display`.

Do you have any thoughts on this? Whatever you decide, it seems easy enough for me to draft a PR; I'd just like to know which way (if any) you like the most. Or if you have other ideas on this matter. (FWIW I would personally be in favor of option 2, which seems cleaner and less disruptive)

**Comment by SimonDanisch** [comment]
Hi,
yes this should be configurable.
Option 2) sounds like the better one, but `toggle_devtools(display.window)` would be nice as well!

**Comment by ffevotte** [comment]
Thanks! Let me draft a PR then. And you're right: let's be greedy too! I'll implement option 2, and try to add some documentation as well about how to toggle devtools on an existing electron display.
