### ISSUE TITLE
Leaflet example not working

### ISSUE THREAD

**Issue by ConnectedSystems** [SimonDanisch/JSServe.jl#193]
Hello,

Just trying out the example from [here](https://simondanisch.github.io/JSServe.jl/stable/#Easy-integration-with-existing-JS-CSS-libraries)

```julia
App() do
    js = ES6Module("https://esm.sh/v111/leaflet@1.9.3/es2022/leaflet.js")
    css = Asset("https://unpkg.com/leaflet@1.9.3/dist/leaflet.css")
    map_div = DOM.div(id="map"; style="height: 300px; width: 100%")
    return DOM.div(
        css, map_div,
        js"""
        $(js).then(L=> {
            const map = L.map('map').setView([51.505, -0.09], 13);
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
        })
        """
    )
end
```

Opens up a blank page with this error message in the console:

```
L.map is not a function
```

**Comment by SimonDanisch** [comment]
Ugh, `esm.sh` changed their api, for now obvious reason -.-
https://github.com/SimonDanisch/JSServe.jl/pull/194

**Comment by ConnectedSystems** [comment]
Thanks, but it still loads up a blank screen. Console error states:

`Loading module from “http://localhost:9385/assets/3d56e88b0ca62ffadc1598a109b71ee4f21fb464-leaflet.bundled.mjs” was blocked because of a disallowed MIME type (“application/octet-stream”).`

I've checked both Edge and Firefox.

**Comment by SimonDanisch** [comment]
Ah really? For me it works on edge, brave and firefox...
<img width="929" alt="image" src="https://github.com/SimonDanisch/JSServe.jl/assets/1010467/7fc6ab1e-c2fb-474f-b69b-03e91fce208c">
I think you're not on the newest version?

**Comment by ConnectedSystems** [comment]
Hmmm... as far as I can tell, I am?

```julia
(proto-webdria) pkg> status JSServe
Status `C:\...\Project.toml`
  [824d6782] JSServe v2.2.13


using JSServe, Hyperscript, Colors
import JSServe.TailwindDashboard as D


App() do
    js = ES6Module("https://esm.sh/v133/leaflet@1.9.4/es2022/leaflet.mjs")
    css = Asset("https://unpkg.com/leaflet@1.9.4/dist/leaflet.css")
    map_div = DOM.div(id="map"; style="height: 300px; width: 100%")
    return DOM.div(
        css, map_div,
        js"""
        $(js).then(L=> {
            const map = L.map('map').setView([51.505, -0.09], 13);
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
        })
        """
    )
end
```

Loads up a blank page.

In the console:

```
Uncaught (in promise) TypeError: L.map is not a function
    <anonymous> http://localhost:9384/browser-display:26

```
