### ISSUE TITLE
document Blink usage?

### ISSUE THREAD

**Issue by piever** [SimonDanisch/JSServe.jl#22]
Hi Simon,
Really nice stuff here! I wanted to start and play with this for an "InteractLight" that minimizes the use of Julia/JavaScript libraries. Do you have a simple snippet to use this with Blink? Maybe it's obvious how to use this in Blink but I couldn't quite figure it out.

**Comment by SimonDanisch** [comment]
So blink isn't really supported...
```Julia
with_session() do session, request
   return DOM.div("hi")
end
```
Should show in the Atom plotpane though and also in the browser under `localhost:8081/show`.
If you want to display an app in a standalone electron window use:
```julia
using Electron, JSServe

app = JSServe.Application("0.0.0.0", 8081) do session, request
    return JSServe.DOM.div("hello world")
end
win = Electron.Window(Electron.URI("http://localhost:8081"))

```
