### ISSUE TITLE
Support Observable{Vector}

### ISSUE THREAD

**Issue by piever** [SimonDanisch/JSServe.jl#24]
For some widgets, it is useful to call `Hyperscript.m` (or the `DOM.tag` analog) with an `Observable{Vector}`, for example when implementing a dropdown menu, whose entries may change.
`m` accepts both an iterable and many arguments, for example

```julia
m("div", [1, 2, 3]) == m("div", 1, 2, 3)
```

However `JSServe.DOM.div(Observable([1, 2, 3]))` renders as `3-element Array{Int64,1}: 1 2 3`, unlike `JSServe.DOM.div([1, 2, 3])` that renders as `123`.

If we do not want to keep both syntaxes, I would prefer `JSServe.DOM.tag(v #= iterable =#; kwargs...)` over the multi-argument method for the reasons mentioned above.

PS: related question, what is the distinction between `JSServe.DOM.tag` and `m("tag")`?

**Comment by piever** [comment]
A "challenge" for the current implementation is to do a "dropdown" menu (`<select>` tag), where both the options and the value are `Observable`s. The options should iterate key, value pairs, where the key determines what's written on the dropdown menu, and the value of the dropdown determins which option is selected (the one with the same value).

**Comment by SimonDanisch** [comment]
I think one should just map over the observable and return the sub tree div inside the map...
I wouldn't really like to auto expand a vector!
Maybe, if it turns out to be really important, we can add an unzip construct, or something like that ;)
