### ISSUE TITLE
How to "unset" boolean attributes using observables?

### ISSUE THREAD

**Issue by piever** [SimonDanisch/JSServe.jl#27]
It's great that one can do `DOM.div(; some_attr = o::Observable)` in general. The problem is that with boolean attributes, every value sets it, so changing the observable does not do anything.

It may be better to have some special struct to unset it, say a `struct UnsetAttribute end` such that if  `some_attr=UnsetAttribute()`, then the attribute is not set. WebIO uses `nothing` for this, but in Hyperscript that means "set the attribute with no value".

**Comment by SimonDanisch** [comment]
closed in #35
